application: smsmybus-hrd
version: python-upgrade
runtime: python27
api_version: 1
threadsafe: false

derived_file_type:
- python_precompiled

inbound_services:
- mail
- xmpp_message

builtins:
- appstats: off
- remote_api: off

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:

- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /service-plan
  static_files: public/service-plan.html
  upload: public/service-plan.html

- url: /(.*html)
  static_files: public/\1
  upload: public/(.*html)

- url: /gadgets/metro/.*
  script: apps/gadgets/gadget.py

- url: /js
  static_dir: public/js

- url: /css
  static_dir: public/css

- url: /img/(.*)
  static_files: public/img/\1
  upload: public/img/(.*)

- url: /favicon.ico
  static_files: public/img/favicon.ico
  upload: public/img/favicon.ico

- url: /apple-touch-icon.png
  static_files: public/img/apple-touch-icon.png
  upload: public/img/apple-touch-icon.png

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /loggingtask
  script: main.py
  login: admin

#
# ADMIN access
#
- url: /admin.*
  script: admin.application
  login: admin

#
# SMS service
#
- url: /sms/.*
  script: apps.sms.application

#
# XMPP service
#
- url: /_ah/xmpp/.*
  script: apps.xmpp.application

#
# PHONE service
#
- url: /phone/.*
  script: apps.phone.application

#
# Email service
#
- url: /_ah/mail/.+
  script: apps.electric_mail.application
  login: admin

#
# Custom kiosk displays
#
- url: /kiosk
  script: apps.kiosk.kiosk.app

- url: /motherfools.*
  static_files: public/kiosk/motherfools/index.html
  upload: public/kiosk/motherfools/index.html

- url: /supranet.*
  static_files: public/kiosk/supranet/index.html
  upload: public/kiosk/supranet/index.html

- url: /sector67.*
  static_files: public/kiosk/sector67/index.html
  upload: public/kiosk/sector67/index.html

#
# catch all...
#
- url: /.*
  script: main.application

#admin_console:
# pages:
# - name: Appstats
#   url: /stats